# Discord Bot Configuration
discord:
  bot-token: "YOUR_BOT_TOKEN_HERE"
  channel-id: "YOUR_CHANNEL_ID_HERE"
  guild-id: "YOUR_GUILD_ID_HERE"

# OTP Settings
otp:
  code-length: 6
  expiration-minutes: 5
  max-attempts: 3
  cooldown-seconds: 30

# IP Tracking Settings
ip-tracking:
  enabled: true
  log-player-ips: true
  max-accounts-per-ip: 5
  alert-on-ip-limit: true

# Messages
messages:
  prefix: "§6[OTP] §r"
  no-permission: "§cBạn không có quyền sử dụng lệnh này!"
  usage-otp: "§eSử dụng: /otp <mã>"
  usage-reload: "§eSử dụng: /discordotp reload"
  usage-ipcheck: "§eSử dụng: /ipcheck <ip>"
  config-reloaded: "§aCấu hình đã được reload thành công!"
  invalid-code: "§cMã OTP không hợp lệ!"
  code-expired: "§cMã OTP đã hết hạn!"
  max-attempts-reached: "§cBạn đã đạt giới hạn thử lại. Vui lòng đợi!"
  cooldown-active: "§cVui lòng đợi {time} giây trước khi thử lại!"
  auth-success: "§aXác thực thành công!"
  auth-failed: "§cXác thực thất bại!"
  code-sent: "§aMã OTP đã được gửi đến Discord của bạn!"
  no-discord-linked: "§cBạn chưa liên kết Discord với tài khoản này!"
  already-authenticated: "§aBạn đã xác thực rồi!"
  ip-limit-reached: "§cIP này đã đạt giới hạn tài khoản ({max})!"
  ip-info-header: "§6=== Thông tin IP ==="
  ip-info-ip: "§eIP: §f{ip}"
  ip-info-accounts: "§eSố tài khoản: §f{count}"
  ip-info-accounts-list: "§eDanh sách tài khoản:"
  ip-info-account-name: "§7- {name}"
