name: DiscordOTPAuth
version: 1.0.0
main: haoyidev.discordotpauth.DiscordOTPAuth
api-version: '1.21'
author: haoyidev
description: Plugin xác thực OTP qua Discord cho Minecraft server
commands:
  otp:
    description: Lệnh xác thực OTP
    usage: /otp <mã_otp>
    aliases: [otpauth]
  discordotp:
    description: Lệnh quản lý DiscordOTPAuth
    usage: /discordotp reload
    aliases: [dauth, discordauth]
permissions:
  discordotp.reload:
    description: Cho phép reload DiscordOTPAuth plugin
    default: op
  discordotp.use:
    description: Cho phép sử dụng lệnh OTP
    default: true
